name: Docker Compose CI

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Private Registry
        uses: docker/login-action@v1
        with:
          registry: docker.wso2.com
          username: ${{ secrets.WSO2_SUB_USER }}
          password: ${{ secrets.WSO2_SUB_PASS }}
      - uses: actions/checkout@v2
      - name: Download components
        run: docker-compose -f bootstrap/components.yml up && docker-compose -f bootstrap/components.yml down
      - name: Build the stack
        run: docker-compose up -d
      - name: Test Idenity server started
        run: docker run --network is-guides appropriate/curl -kv --retry 10 --retry-connrefused https://identity-server:9443/api/health-check/v1.0/health
